<?php

namespace s2\todoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

    private $table = "events";

    public function myfindAll($public = false) {
        $qb = $this->createQueryBuilder($this->table);

        if ($public) {
            $qb->where($this->table . '.public = 1');
        }

        $qb->leftJoin($this->table . ".tags", "t")->addSelect("t");

        return $qb->getQuery()->getResult();
    }

    public function myfindOne($id, $public = false) {
        $qb = $this->createQueryBuilder($this->table);

        $qb->where($this->table . '.id = :id')
                ->setParameter('id', $id)
                ->leftJoin($this->table . ".tags", "t")
                ->addSelect("t")
        ;
        if ($public) {
            $qb->AndWhere($this->table . '.public = 1');
        }

        return $qb->getQuery()->getSingleResult();
    }

}
